#!/bin/sh
#
# Runs before git flow feature finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
NAME=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.

# -- START -- not ready for use with dev team.
# echo "Branch is: $BRANCH"
# current_version="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
# echo "Current version is: $current_version"
# export old_version=$current_version
# echo "export gitflow_pre_version=$current_version" >> $TMPDIR/git_pre_ver.sh
# -- FINISH -- not ready for use with dev team.

# To terminate the git-flow action, return a non-zero exit code.
exit 0
